### ISSUE TITLE
Compatibility with Cake 0.22 or higher

### ISSUE THREAD

**Issue by ccellar** [cake-contrib/Cake.Paket#18]
Thanks a lot for the paket integration into cake. As Cake.Paket currently references Cake 0.21, we have some versioning issues when trying to upgrade Cake. See https://cakebuild.net/blog/2017/09/cake-v0.22.0-released
Do you plan to update the module in the nearer future, or should we provide a PR?

**Comment by larzw** [comment]
Glad you find it useful. I'd definitely accept a PR for this. I could probably get a release out this weekend if you can wait this long.

**Comment by ccellar** [comment]
@larzw do you plan to create a new release anytime soon?

**Comment by larzw** [comment]
Yes..I Will try and get one out this week.

**Comment by larzw** [comment]
@ccellar, I just released it on nuget. Sorry about it taking so long! Let me know if you have any other problems.

**Comment by ccellar** [comment]
No worries. Thanks a lot!
