### ISSUE TITLE
Need new maintainer

### ISSUE THREAD

**Issue by larzw** [cake-contrib/Cake.Paket#25]
If your interested in becoming the maintainer of Cake.Paket and Cake.Paket.Module let me know and I can get you setup. Thanks!

**Comment by gep13** [comment]
@larzw thank you very much for your work on this addin/module to date, we really appreciate it!

Now that we have some instructions written here:

https://github.com/cake-contrib/Cake.Paket/wiki/Maintainers

I am happy to help with keeping things ticking along with this addin/module  (i.e. bumping Cake version, etc.)  If anyone is interested in taking over full maintenance of this addin/module, then definitely get in touch.

**Comment by gep13** [comment]
@larzw did you get someone to help as being a maintainer?
